"""empty message

Revision ID: ce11f40d0d74
Revises: 2bc02a84864b
Create Date: 2021-06-05 14:32:36.430999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce11f40d0d74'
down_revision = '2bc02a84864b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('mac', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'thing', ['mac'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thing', type_='unique')
    op.drop_column('thing', 'mac')
    # ### end Alembic commands ###
