# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 5432, host: 15432
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"

  config.vm.synced_folder "./projeto", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "focal64_sqlalchemy"
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.provision :shell, :path => "Vagrant-setup/bootstrap.sh"
end
